name: Create release and deploy

on:
  push:
    tags:
      - 'v*' # Запускать пайплайн при пуше тега, начинающегося с 'v', например v1.0.0

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 4. Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            latest

      # 5. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  create-release:
    needs: build-test-push
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          body: |
            ## Docker Images
      
            This release includes the following Docker images:
      
            - `ghcr.io/${{ github.repository }}:${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository }}:latest`
      
            ### Deployment
      
            ```bash
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            docker compose -f docker-compose.yml up -d
            ```
   deploy:
    needs: [build-test-push, create-release] # Запускать только после сборки и создания релиза
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Создаем временный файл конфигурации из секрета
      - name: Create config file from secret
        run: |
          cat << EOF > appsettings.Production.json
          ${{ secrets.APPSETTINGS_PROD }}
          EOF

      # Копируем конфиг на сервер
      - name: Copy config to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "appsettings.Production.json"
          target: "/opt/NVRNotifier/config/"
      
      # 2. Deploy to server via SSH
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Критически важные команды:
          script: |
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker-compose -f docker-compose.yml down

            docker pull ghcr.io/${{ github.repository }}:latest

            docker-compose -f docker-compose.yml up -d

            docker image prune -f